### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by Waissi** [alessandrofama/fmod-love#2]

**Comment by YoannClaude** [comment]
For some reason opening the project after switching back to Zerobrane studio from VSCode solved the problem.
I really wonder why but at least I have the library working now :D

**Comment by YoannClaude** [comment]
I guess I figured out what happens: it seems that VSCode and Zerobrane don't manage paths the same way.
In any case, I suggest using love.filesystem.getSourceBaseDirectory() for loading both lib and banks, to prevent issues after building the .love file.
